### ISSUE TITLE
not connected to victim

### ISSUE THREAD

**Issue by CHAsif99** [thatcherclough/BetterBackdoor#21]
I have follow all the instructions but when i send the backdoor (run.jar & run.bat )to victim and go to my kali  linux2020 machine and try to connect the victime by running backdoor on his computer(using windows 10) nothing happens

**Comment by ThatcherDev** [comment]
Interesting. Are the two computers on the same WiFi network and did you select 'internal' IP when creating the backdoor?

**Comment by CHAsif99** [comment]
yes i did the same as you describe

**Comment by ThatcherDev** [comment]
From my experience this is most likely a firewall issue. what happens if you run both programs (betterbackdoor.jar and run.jar) on the same kali machine and try to connect?

**Comment by ThatcherDev** [comment]
Did you ever try running both programs (betterbackdoor.jar and run.jar) on the same kali machine and connecting?

**Comment by ThatcherDev** [comment]
Also when performing this test make sure to re run option 0 at start so that the backdoor has the right IP address.

**Comment by thatcherclough** [comment]
If this issue persists, please create a new bug issue.
