### ISSUE TITLE
AES 256 Encryptation not working 

### ISSUE THREAD

**Issue by gab-villa** [thatcherclough/BetterBackdoor#28]
i tried to use AES 256 encryptation but i had a problem when the program read this line on backend/utils.java:
cipher.init(Cipher.ENCRYPT_MODE, encryptionKey);
The problem makes the program doesn't accept the key.
I found a solution: use AES 128, and i think the reason is because i need a specific library that i don't know for AES 256
I use Linux Mint 18.2

**Comment by gab-villa** [comment]
I found this and i'm sure this is the reason explained.

"Por defecto Java solo soporta 128-bit a la hora de encriptar.

Esto equivale a 16 carácteres. Por lo que la cadena a encriptar: "the quick brown fox jumps over the lazy dog" no es válida.

Si vas a encriptar algo que contenga más de 16 carácteres deberás de instalarte la extensión Java Cryptography Extension (JCE) Unlimited Strength."

link: https://es.stackoverflow.com/questions/55465/error-al-encriptar-exception-in-thread-main-java-security-invalidkeyexception

**Comment by thatcherclough** [comment]
Thank you for this. I will change the encryption to use 128 bit keys. I'll let you know when I implement this, that way you can test it out before I release!

**Comment by thatcherclough** [comment]
I just pushed an update to the "develop" branch that should fix it. Clone it using ``` git clone -b develop https://github.com/thatcherclough/BetterBackdoor.git```. Let me know if it works!

**Comment by thatcherclough** [comment]
As of release 1.14.1, this has been fixed.
